import { jsPDF } from 'jspdf'
import TurndownService from 'turndown'

// Generate PDF directly from text content without html2canvas
// This avoids the oklch/lab color parsing issues
export async function exportToPDF(
  element: HTMLElement,
  filename: string
) {
  try {
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    })

    const pageWidth = pdf.internal.pageSize.getWidth()
    const margin = 20
    const maxWidth = pageWidth - 2 * margin
    let yPosition = margin

    // Add title
    pdf.setFontSize(24)
    pdf.setFont('helvetica', 'bold')
    pdf.text(filename, margin, yPosition)
    yPosition += 15

    // Add horizontal line
    pdf.setDrawColor(200, 200, 200)
    pdf.line(margin, yPosition, pageWidth - margin, yPosition)
    yPosition += 10

    // Extract text content from the editor element
    const tiptapEditor = element.querySelector('.tiptap')
    if (tiptapEditor) {
      // Process each child element
      const children = tiptapEditor.children
      for (let i = 0; i < children.length; i++) {
        const child = children[i] as HTMLElement
        const tagName = child.tagName.toLowerCase()
        const text = child.textContent || ''

        if (!text.trim()) continue

        // Check if we need a new page
        if (yPosition > 270) {
          pdf.addPage()
          yPosition = margin
        }

        if (tagName === 'h1') {
          pdf.setFontSize(20)
          pdf.setFont('helvetica', 'bold')
          const lines = pdf.splitTextToSize(text, maxWidth)
          pdf.text(lines, margin, yPosition)
          yPosition += lines.length * 8 + 6
        } else if (tagName === 'h2') {
          pdf.setFontSize(16)
          pdf.setFont('helvetica', 'bold')
          const lines = pdf.splitTextToSize(text, maxWidth)
          pdf.text(lines, margin, yPosition)
          yPosition += lines.length * 7 + 5
        } else if (tagName === 'h3') {
          pdf.setFontSize(14)
          pdf.setFont('helvetica', 'bold')
          const lines = pdf.splitTextToSize(text, maxWidth)
          pdf.text(lines, margin, yPosition)
          yPosition += lines.length * 6 + 4
        } else if (tagName === 'ul' || tagName === 'ol') {
          pdf.setFontSize(11)
          pdf.setFont('helvetica', 'normal')
          const listItems = child.querySelectorAll('li')
          listItems.forEach((li, index) => {
            const bullet = tagName === 'ul' ? '•' : `${index + 1}.`
            const itemText = li.textContent || ''
            const lines = pdf.splitTextToSize(`${bullet} ${itemText}`, maxWidth - 5)
            pdf.text(lines, margin + 5, yPosition)
            yPosition += lines.length * 5 + 2
          })
          yPosition += 3
        } else if (tagName === 'blockquote') {
          pdf.setFontSize(11)
          pdf.setFont('helvetica', 'italic')
          pdf.setTextColor(100, 100, 100)
          const lines = pdf.splitTextToSize(text, maxWidth - 10)
          // Draw quote bar
          pdf.setDrawColor(150, 150, 150)
          pdf.setLineWidth(0.5)
          pdf.line(margin, yPosition - 3, margin, yPosition + lines.length * 5)
          pdf.text(lines, margin + 5, yPosition)
          pdf.setTextColor(0, 0, 0)
          yPosition += lines.length * 5 + 5
        } else {
          // Default paragraph
          pdf.setFontSize(11)
          pdf.setFont('helvetica', 'normal')
          const lines = pdf.splitTextToSize(text, maxWidth)
          pdf.text(lines, margin, yPosition)
          yPosition += lines.length * 5 + 4
        }
      }
    } else {
      // Fallback: just get all text content
      pdf.setFontSize(11)
      pdf.setFont('helvetica', 'normal')
      const text = element.textContent || 'No content'
      const lines = pdf.splitTextToSize(text, maxWidth)
      pdf.text(lines, margin, yPosition)
    }

    // Add footer
    const pageCount = pdf.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(9)
      pdf.setTextColor(150, 150, 150)
      pdf.text(
        `Page ${i} of ${pageCount} - Generated by Scribe`,
        pageWidth / 2,
        290,
        { align: 'center' }
      )
    }

    pdf.save(`${filename}.pdf`)
  } catch (err) {
    console.error('Error exporting to PDF:', err)
    throw err
  }
}

export function exportToMarkdown(
  content: Record<string, unknown>,
  filename: string
) {
  try {
    const turndownService = new TurndownService({
      headingStyle: 'atx',
      bulletListMarker: '-',
      codeBlockStyle: 'fenced',
    })

    // Convert content to HTML first
    const html = convertContentToHTML(content)
    const markdown = turndownService.turndown(html)

    const dataBlob = new Blob([markdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(dataBlob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${filename}.md`
    link.click()
    URL.revokeObjectURL(url)
  } catch (err) {
    console.error('Error exporting to Markdown:', err)
  }
}

function convertContentToHTML(content: Record<string, unknown>): string {
  if (
    !content.content ||
    !Array.isArray(content.content)
  ) {
    return '<p>No content</p>'
  }

  const contentArray = content.content as Array<Record<string, unknown>>
  return contentArray
    .map(node => {
      if (node.type === 'heading') {
        const level = node.attrs?.level || 1
        const text = getTextFromNode(node)
        return `<h${level}>${text}</h${level}>`
      } else if (node.type === 'paragraph') {
        const text = getTextFromNode(node)
        return `<p>${text}</p>`
      } else if (node.type === 'bulletList' || node.type === 'orderedList') {
        const tag = node.type === 'bulletList' ? 'ul' : 'ol'
        const items = (node.content as Array<Record<string, unknown>>) || []
        const itemsHTML = items
          .map(item => `<li>${getTextFromNode(item)}</li>`)
          .join('')
        return `<${tag}>${itemsHTML}</${tag}>`
      } else if (node.type === 'codeBlock') {
        const text = getTextFromNode(node)
        return `<pre><code>${text}</code></pre>`
      } else if (node.type === 'blockquote') {
        const text = getTextFromNode(node)
        return `<blockquote>${text}</blockquote>`
      }
      return ''
    })
    .join('')
}

function getTextFromNode(node: Record<string, unknown>): string {
  if (!node.content) {
    return ''
  }

  if (Array.isArray(node.content)) {
    return node.content
      .map(item => {
        if (typeof item === 'object' && item !== null && 'text' in item) {
          const textNode = item as Record<string, unknown>
          let text = String(textNode.text || '')

          if (textNode.marks) {
            const marks = textNode.marks as Array<Record<string, unknown>>
            marks.forEach(mark => {
              if (mark.type === 'bold') {
                text = `<strong>${text}</strong>`
              } else if (mark.type === 'italic') {
                text = `<em>${text}</em>`
              } else if (mark.type === 'underline') {
                text = `<u>${text}</u>`
              } else if (mark.type === 'code') {
                text = `<code>${text}</code>`
              }
            })
          }

          return text
        }
        return ''
      })
      .join('')
  }

  return ''
}
